use std::fs;
use std::path::Path;

use lsw_config::{ResolvedToolchain, TargetArch};

use crate::util::which;

pub fn write_cmake_toolchain_file(
    path: &Path,
    tc: &ResolvedToolchain,
    arch: TargetArch,
) -> std::io::Result<()> {
    let processor = match arch {
        TargetArch::X86_64 => "AMD64",
        TargetArch::X86 => "X86",
        TargetArch::Aarch64 | TargetArch::Arm64Ec => "ARM64",
        TargetArch::Armv7 => "ARM",
    };
    let c_flags = tc.c_flags.join(" ");
    let cxx_flags = tc
        .c_flags
        .iter()
        .chain(&tc.cxx_flags)
        .cloned()
        .collect::<Vec<_>>()
        .join(" ");
    let link_flags = tc.link_flags.join(" ");

    let mut text = String::new();
    text.push_str("# Generated by lsw-toolchain; do not edit.\n");
    text.push_str("set(CMAKE_SYSTEM_NAME Windows)\n");
    text.push_str(&format!("set(CMAKE_SYSTEM_PROCESSOR {processor})\n"));
    text.push_str(&format!("set(CMAKE_C_COMPILER \"{}\")\n", tc.cc.display()));
    text.push_str(&format!(
        "set(CMAKE_CXX_COMPILER \"{}\")\n",
        tc.cxx.display()
    ));
    text.push_str(&format!("set(CMAKE_C_FLAGS_INIT \"{c_flags}\")\n"));
    text.push_str(&format!("set(CMAKE_CXX_FLAGS_INIT \"{cxx_flags}\")\n"));
    text.push_str(&format!(
        "set(CMAKE_EXE_LINKER_FLAGS_INIT \"{link_flags}\")\n"
    ));
    text.push_str(&format!(
        "set(CMAKE_SHARED_LINKER_FLAGS_INIT \"{link_flags}\")\n"
    ));
    text.push_str(&format!(
        "set(CMAKE_FIND_ROOT_PATH \"{}\")\n",
        tc.sysroot.display()
    ));
    text.push_str("set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)\n");
    text.push_str("set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)\n");
    text.push_str("set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)\n");
    if let Some(windres) = which(&format!("{}-windres", arch.mingw_triple())) {
        text.push_str(&format!(
            "set(CMAKE_RC_COMPILER \"{}\")\n",
            windres.display()
        ));
    }
    text.push_str("set(CMAKE_EXECUTABLE_SUFFIX \".exe\")\n");
    fs::write(path, text)
}
