name: Publish VS Code extension

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    name: vsce publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: editors/vscode
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
